name: Build and Push to ACR

on:
  push:
    branches: [ main ]  # or your deployment branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Docker Login to ACR
      run: az acr login --name demowebapp1221

    - name: Build Docker Image
      run: docker build -t demowebapp1221.azurecr.io/demowebapp1221:latest .

    - name: Push Docker Image
      run: docker push demowebapp1221.azurecr.io/demowebapp1221:latest
