name: Build, Push Docker Image and Deploy to Web App

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
   
    - name: Login to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: demowebapp12.azurecr.io
        login-server: demowebapp12.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Match the version used in Dockerfile

    - name: Build Docker Image
      run: docker build -t demowebapp12.azurecr.io/demowebapp12:latest -f VSRAdminAPI/Dockerfile .

    - name: Push Docker Image to ACR
      run: docker push demowebapp12.azurecr.io/demowebapp12:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Configure Web App to use ACR Image
      uses: azure/webapps-container-deploy@v2
      with:
        app-name: 'your-web-app-name'  # Replace with your web app name
        images: 'demowebapp12.azurecr.io/demowebapp12:latest'
        registry-server: 'demowebapp12.azurecr.io'
        registry-username: ${{ secrets.ACR_USERNAME }}
        registry-password: ${{ secrets.ACR_PASSWORD }}
