name: Build, Push and Deploy with Swagger

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
   
    - name: Login to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: demowebapp12.azurecr.io
        username: ${{ secrets.DOCKERIO_USERNAME }}
        password: ${{ secrets.DOCKERIO_PASSWORD }}

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build Docker Image
      run: |
        docker build \
          -t demowebapp12.azurecr.io/demowebapp12:latest \
          -f VSRAdminAPI/Dockerfile \
          --build-arg ASPNETCORE_ENVIRONMENT=Production \
          --build-arg SWAGGER_ENABLED=true \
          .

    - name: Push Docker Image to ACR
      run: docker push demowebapp12.azurecr.io/demowebapp12:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      run: |
        # Configure container settings
        az webapp config container set \
          --name mydemo1221-appservice \
          --resource-group demowebapp1221 \
          --docker-custom-image-name demowebapp12.azurecr.io/demowebapp12:latest \
          --docker-registry-server-url https://demowebapp12.azurecr.io \
          --docker-registry-server-user ${{ secrets.ACR_USERNAME }} \
          --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}

        # Configure app settings for Swagger
        az webapp config appsettings set \
          --name mydemo1221-appservice \
          --resource-group demowebapp1221 \
          --settings \
            ASPNETCORE_ENVIRONMENT=Production \
            SWAGGER_ENABLED=true

        # Restart the web app to apply changes
        az webapp restart --name mydemo1221-appservice --resource-group demowebapp1221
