name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
   
    - name: Login to Azure Container Registry
      uses: docker/login-action@v2
      with:
       registry: demowebapp12.azurecr.io
       login-server: demowebapp12.azurecr.io
       username: ${{ secrets.DOCKERIO_USERNAME }}
       password: ${{ secrets.DOCKERIO_PASSWORD }}

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Match the version used in Dockerfile

    - name: Build Docker Image
      run: docker build -t demowebapp1221.azurecr.io/demowebapp12:latest -f VSRAdminAPI/Dockerfile .


    - name: Push Docker Image to ACR
      run: docker push demowebapp1221.azurecr.io/demowebapp12:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # Set in GitHub Secrets as JSON credentials

    - name: Deploy to Azure Web App
      run: |
        az webapp create --resource-group myResourceGroup \
                         --name myAppService \
                         --plan demo-webapp \
                         --deployment-container-image-name demowebapp1221.azurecr.io/:latest
